language: go

services:
    - docker

go:
    - "1.10"
    - "1.9"

before_script:
    - env | sort
    - mkdir secrets
    - echo $GITHUB_ACCESS_TOKEN > secrets/access_token.txt

script:
    # Make sure if project is building
    - make build
    # Testing the project
    - docker run -d -p 27017:27017 mongo
    - packr
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic
    - packr clean

after_success:
    - bash <(curl -s https://codecov.io/bash)
