language: go

services:
    - docker

go:
    - "1.10"
    - "1.9"

before_script:
    - env | sort
    - mkdir secrets

script:
    - make build env=devel
    - docker run -d -p 27017:27017 mongo
    - packr
    - go test -v -race -tags devel -coverprofile=coverage.txt -covermode=atomic
    - packr clean

after_success:
    - bash <(curl -s https://codecov.io/bash)
