version: '3'
services:
    web:
        build: .
        image: github-flair-web:prod
        ports:
            - "443:443"
    mongo:
        image: "mongo:latest"
        ports:
            - "27017"
