version: '3.3'
services:
    web:
        build: .
        image: github-flair-web:prod
        volumes:
            - data-volume:/data
        ports:
            - "443:443"
    mongo:
        image: mongo:latest
        volumes:
            - data-volume:/data
volumes:
    data-volume:
